const CREATE_TOOLS = 1;
const UPDATE_TOOLS = 2;
const DELETE_TOOLS = 3;
const EDIT_BUTTON = 4;
const RESET_FORM = 5;
const SET_LOADING = 6;
const FETCH_COMPLETE = 7;
const HANDLE_INPUT_CHANGES = 8;
const SUBMIT_COMPLETE = 9;

export {
    CREATE_TOOLS, UPDATE_TOOLS, DELETE_TOOLS, EDIT_BUTTON, RESET_FORM, SET_LOADING, FETCH_COMPLETE, HANDLE_INPUT_CHANGES, SUBMIT_COMPLETE
}