const CREATE_JOB = 1;
const UPDATE_JOB = 2;
const DELETE_JOB = 3;
const EDIT_BUTTON = 4;
const RESET_FORM = 5;
const SET_LOADING = 6;
const FETCH_COMPLETE = 7;
const HANDLE_INPUT_CHANGES =8;
const SUBMIT_COMPLETE = 9;
const HANDLE_INPUT_TOOL = 10;

export{
    CREATE_JOB, UPDATE_JOB, DELETE_JOB      , EDIT_BUTTON, RESET_FORM, SET_LOADING, FETCH_COMPLETE, HANDLE_INPUT_CHANGES, SUBMIT_COMPLETE,
    HANDLE_INPUT_TOOL
}